/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIProfile */
        AIProfile: {
            /**
             * Active
             * @default false
             */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Parameters */
            parameters: {
                [key: string]: (number | string) | string | number | boolean;
            };
            /** Profile Key */
            profile_key: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
            /** Version */
            version: number;
        };
        /** AIProfileRecommendation */
        AIProfileRecommendation: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Evidence Session Ids */
            evidence_session_ids: string[];
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Profile Id
             * Format: uuid
             */
            profile_id: string;
            /** Rationale */
            rationale: string;
            /** Recommended Parameters */
            recommended_parameters: {
                [key: string]: (number | string) | string | number | boolean;
            };
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** @default proposed */
            state: components["schemas"]["RecommendationState"];
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
        };
        /** AuditEvent */
        AuditEvent: {
            /** Actor Type */
            actor_type: string;
            /**
             * Aggregate Id
             * Format: uuid
             */
            aggregate_id: string;
            /** Aggregate Type */
            aggregate_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Event Type */
            event_type: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Payload Digest */
            payload_digest: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
        };
        /** AuthMeResponse */
        AuthMeResponse: {
            /** Authenticated */
            authenticated: boolean;
            /** Email */
            email: string;
        };
        /** AuthorizationDecision */
        AuthorizationDecision: {
            /**
             * Account Observed At
             * Format: date-time
             */
            account_observed_at: string;
            /** Account Verified */
            account_verified: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Proposal Digest */
            proposal_digest: string;
            /**
             * Proposal Id
             * Format: uuid
             */
            proposal_id: string;
            /** Ruleset Version */
            ruleset_version: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            state: components["schemas"]["AuthorizationState"];
            /** Supported Options Level */
            supported_options_level: number;
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
        };
        /**
         * AuthorizationState
         * @enum {string}
         */
        AuthorizationState: "accepted" | "rejected" | "modified_pending_acceptance";
        /** EvidenceItem */
        EvidenceItem: {
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Source */
            source: string;
            /** Summary */
            summary: string;
        };
        /** ExecutionReceipt */
        ExecutionReceipt: {
            /**
             * Broker Order Id
             * @default null
             */
            broker_order_id: string | null;
            /** Client Order Id */
            client_order_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Error Code
             * @default null
             */
            error_code: string | null;
            /**
             * Error Message
             * @default null
             */
            error_message: string | null;
            /**
             * Filled Average Price
             * @default null
             */
            filled_average_price: (number | string) | null;
            /**
             * Filled Quantity
             * Format: decimal-string
             * @default 0
             */
            filled_quantity: number | string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Payload Digest */
            payload_digest: string;
            /**
             * Proposal Id
             * Format: uuid
             */
            proposal_id: string;
            /**
             * Reconciled At
             * @default null
             */
            reconciled_at: string | null;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            status: components["schemas"]["ExecutionStatus"];
            /**
             * Submitted At
             * @default null
             */
            submitted_at: string | null;
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
        };
        /**
         * ExecutionStatus
         * @enum {string}
         */
        ExecutionStatus: "pending" | "submitted" | "reconciling" | "rejected" | "filled" | "failed";
        /** ExitPolicy */
        ExitPolicy: {
            /**
             * Dte Threshold
             * @default 7
             */
            dte_threshold: number;
            /**
             * Max Hold Days
             * @default 14
             */
            max_hold_days: number;
            /**
             * Stop Loss Pct
             * Format: decimal-string
             * @default 50.0
             */
            stop_loss_pct: number | string;
            /**
             * Take Profit Pct
             * Format: decimal-string
             * @default 50.0
             */
            take_profit_pct: number | string;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "ready" | "not_ready";
        };
        /** HistoricalBar */
        HistoricalBar: {
            /**
             * Close
             * Format: decimal-string
             */
            close: number | string;
            /**
             * High
             * Format: decimal-string
             */
            high: number | string;
            /**
             * Low
             * Format: decimal-string
             */
            low: number | string;
            /**
             * Open
             * Format: decimal-string
             */
            open: number | string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Trade Count
             * @default null
             */
            trade_count: number | null;
            /** Volume */
            volume: number;
            /**
             * Vwap
             * @default null
             */
            vwap: (number | string) | null;
        };
        /** HistoricalMarketDataRecord */
        HistoricalMarketDataRecord: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            data_type: components["schemas"]["MarketDataType"];
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Is Immutable
             * @default false
             */
            is_immutable: boolean;
            /** Item Count */
            item_count: number;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Query Digest */
            query_digest: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Source */
            source: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /** Symbol */
            symbol: string;
            /** @default null */
            timeframe: components["schemas"]["TimeFrameKind"] | null;
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
        };
        /** LLMEventAnalysis */
        LLMEventAnalysis: {
            /** Article Id */
            article_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Event Type */
            event_type: string;
            /**
             * Expected Reaction Pct
             * @default null
             */
            expected_reaction_pct: (number | string) | null;
            /** Headline */
            headline: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Model Name */
            model_name: string;
            /** Prompt Version */
            prompt_version: string;
            /** Rationale */
            rationale: string;
            /** Raw Digest */
            raw_digest: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Sentiment */
            sentiment: string;
            /**
             * Significance Score
             * Format: decimal-string
             */
            significance_score: number | string;
            /** Symbol */
            symbol: string;
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Email */
            email: string;
            /** Expires At */
            expires_at: string;
            /** Token */
            token: string;
        };
        /** LogoutResponse */
        LogoutResponse: {
            /**
             * Status
             * @constant
             */
            status: "logged_out";
        };
        /**
         * MarketDataType
         * @enum {string}
         */
        MarketDataType: "bars" | "quotes" | "trades" | "news";
        /** OptionLeg */
        OptionLeg: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Expiration */
            expiration: string;
            option_type: components["schemas"]["OptionType"];
            /**
             * Ratio Qty
             * @default 1
             */
            ratio_qty: number;
            side: components["schemas"]["OptionSide"];
            /**
             * Strike Price
             * Format: decimal-string
             */
            strike_price: number | string;
            /** Symbol */
            symbol: string;
            /**
             * Tradable
             * @default true
             */
            tradable: boolean;
            /** Underlying */
            underlying: string;
        };
        /**
         * OptionSide
         * @enum {string}
         */
        OptionSide: "buy" | "sell";
        /** OptionStrategy */
        OptionStrategy: {
            /**
             * Extended Hours
             * @default false
             * @constant
             */
            extended_hours: false;
            kind: components["schemas"]["StrategyKind"];
            /** Legs */
            legs: components["schemas"]["OptionLeg"][];
            /**
             * Limit Price
             * Format: decimal-string
             */
            limit_price: number | string;
            /**
             * Time In Force
             * @default day
             * @constant
             */
            time_in_force: "day";
        };
        /**
         * OptionType
         * @enum {string}
         */
        OptionType: "call" | "put";
        /**
         * RecommendationState
         * @enum {string}
         */
        RecommendationState: "proposed" | "accepted" | "rejected";
        /** ResearchReport */
        ResearchReport: {
            /**
             * Confidence
             * Format: decimal-string
             */
            confidence: number | string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceItem"][];
            /** Freshness Seconds */
            freshness_seconds: number;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Limitations */
            limitations?: string[];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Symbol */
            symbol: string;
            /** Thesis */
            thesis: string;
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
        };
        /** RiskAssessment */
        RiskAssessment: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Data Fresh */
            data_fresh: boolean;
            /** Findings */
            findings: string[];
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Max Loss
             * Format: decimal-string
             */
            max_loss: number | string;
            /**
             * Proposal Id
             * Format: uuid
             */
            proposal_id: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
            verdict: components["schemas"]["RiskVerdict"];
        };
        /**
         * RiskVerdict
         * @enum {string}
         */
        RiskVerdict: "acceptable" | "concerns" | "reject";
        /** RuleEvaluation */
        RuleEvaluation: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Modified Proposal Digest
             * @default null
             */
            modified_proposal_digest: string | null;
            outcome: components["schemas"]["RuleOutcome"];
            /**
             * Proposal Id
             * Format: uuid
             */
            proposal_id: string;
            /** Reasons */
            reasons: string[];
            /** Ruleset Version */
            ruleset_version: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
        };
        /**
         * RuleOutcome
         * @enum {string}
         */
        RuleOutcome: "pass" | "modify" | "fail";
        /** ShadowCandidate */
        ShadowCandidate: {
            /**
             * Allocation Multiplier
             * Format: decimal-string
             * @default 1.0
             */
            allocation_multiplier: number | string;
            /** Label */
            label: string;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /** @default null */
            strategy: components["schemas"]["OptionStrategy"] | null;
        };
        /** ShadowSession */
        ShadowSession: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Evaluation Policy Version */
            evaluation_policy_version: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Limitations */
            limitations?: string[];
            /** Metrics */
            metrics?: {
                [key: string]: number | string;
            };
            /**
             * Parent Session Id
             * @default null
             */
            parent_session_id: string | null;
            /**
             * Proposal Id
             * Format: uuid
             */
            proposal_id: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            state: components["schemas"]["ShadowState"];
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
            /** Variation */
            variation: {
                [key: string]: unknown;
            };
        };
        /**
         * ShadowState
         * @enum {string}
         */
        ShadowState: "open" | "complete" | "incomplete";
        /**
         * StrategyKind
         * @enum {string}
         */
        StrategyKind: "long_call" | "long_put" | "call_debit_spread" | "put_debit_spread";
        /** SystemStatus */
        SystemStatus: {
            /** Account Verified */
            account_verified: boolean;
            /** Cli Available */
            cli_available: boolean;
            /** Cli Version */
            cli_version: string | null;
            /** Credentials Present */
            credentials_present: boolean;
            /** Execution Enabled */
            execution_enabled: boolean;
            /** Kill Switch Active */
            kill_switch_active: boolean;
            /** Paper Mode */
            paper_mode: boolean;
            /**
             * State
             * @enum {string}
             */
            state: "ready" | "degraded" | "unavailable" | "misconfigured";
            /** Supported Options Level */
            supported_options_level: number | null;
        };
        /**
         * TimeFrameKind
         * @enum {string}
         */
        TimeFrameKind: "1Min" | "5Min" | "15Min" | "1Hour" | "1Day";
        /** TradeProposal */
        TradeProposal: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            exit_policy?: components["schemas"]["ExitPolicy"];
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Proposal Digest */
            proposal_digest: string;
            /** Quantity */
            quantity: number;
            /** Rationale */
            rationale: string;
            /**
             * Research Report Id
             * Format: uuid
             */
            research_report_id: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Shadow Candidates */
            shadow_candidates?: components["schemas"]["ShadowCandidate"][];
            strategy: components["schemas"]["OptionStrategy"];
            /** Symbol */
            symbol: string;
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
