import { Bot, CheckCircle2, ChevronLeft, ListChecks, Network } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

import { SECTION_CARD, SectionHeading } from "@/components/workspace/section-heading";
import { formatTokens } from "@/features/story/formatters";
import { getAgent } from "@/features/story/presentation-api";
import { StoryColumnChart } from "@/features/story/story-charts";
import { RunHistory } from "@/features/agents/run-history";
import { TryAgentButton, type AgentAction } from "@/features/agents/agent-playground-modal";

function mapAgentIdToAction(id: string): AgentAction {
  const lower = id.toLowerCase();
  if (lower.includes("decision") || lower.includes("trading") || lower.includes("cio"))
    return "decision";
  if (lower.includes("fundamental")) return "fundamental";
  if (lower.includes("quant")) return "quant";
  if (lower.includes("industry")) return "industry";
  if (lower.includes("macro")) return "macro";
  if (lower.includes("reaction")) return "reaction";
  if (lower.includes("news")) return "news";
  return "decision";
}

const METRIC_CARD =
  "rounded-xl border border-white/8 border-t-white/16 bg-linear-to-b from-white/6 to-white/2 p-5 backdrop-blur-xl transition-all duration-200 hover:border-[#547D83]/40 hover:shadow-[0_0_24px_rgba(84,125,131,0.35)]";

export default async function AgentDetailPage({
  params,
}: {
  params: Promise<{ agentId: string }>;
}) {
  const { agentId } = await params;
  const agent = await getAgent(agentId);
  if (!agent) notFound();
  const runs = agent.runs;
  const inputTokens = runs.reduce((total, run) => total + run.inputTokens, 0);
  const outputTokens = runs.reduce((total, run) => total + run.outputTokens, 0);
  const cachedTokens = runs.reduce((total, run) => total + run.cachedTokens, 0);
  const tokens = inputTokens + outputTokens + cachedTokens;
  const averageDuration = runs.length
    ? Math.round(runs.reduce((total, run) => total + run.durationMs, 0) / runs.length)
    : 0;

  const tokenBreakdown = [
    { label: "Input", value: String(inputTokens), description: "Prompt tokens sent to the model." },
    {
      label: "Output",
      value: String(outputTokens),
      description: "Tokens generated by the model.",
    },
    {
      label: "Cached",
      value: String(cachedTokens),
      description: "Reused cached prompt tokens.",
    },
  ];

  const metrics = [
    { label: "Runs", value: String(runs.length), detail: "Recorded history" },
    { label: "Visible tokens", value: formatTokens(tokens), detail: "No hidden reasoning" },
    {
      label: "Average duration",
      value: runs.length ? `${averageDuration} ms` : "\u2014",
      detail: "Fixture latency",
    },
  ];
  const runItems = runs.map((run) => ({
    id: run.id,
    trigger: run.trigger,
    status: run.status,
    occurredAt: run.occurredAt,
    summary: run.summary,
    durationMs: run.durationMs,
    inputTokens: run.inputTokens,
    outputTokens: run.outputTokens,
    cachedTokens: run.cachedTokens,
  }));
  const anchor = new Date().toISOString().slice(0, 10);

  return (
    <div className="space-y-8">
      <Link
        href="/agents"
        className="inline-flex items-center gap-1.5 text-[12px] text-[#64748B] outline-none transition-colors hover:text-[#CBD5E1] focus-visible:ring-2 focus-visible:ring-[#547D83] focus-visible:ring-offset-2 focus-visible:ring-offset-[#080B10]"
      >
        <ChevronLeft className="h-3.5 w-3.5" aria-hidden="true" />
        All agents and tools
      </Link>

      {/* Agent identity: avatar + name + Try button, with responsibility/model inside */}
      <div className={`${SECTION_CARD} p-5 sm:p-6`}>
        <div className="flex flex-wrap items-center gap-4">
          <span aria-hidden="true" className="relative shrink-0">
            <span className="grid h-12 w-12 place-items-center rounded-lg border border-[#547D83]/40 bg-[#547D83]/15 text-[#B2D8DC]">
              <Bot className="h-6 w-6" />
            </span>
            <span className="absolute -bottom-0.5 -right-0.5 h-3.5 w-3.5 rounded-full border-2 border-[#0B0F14] bg-[#00D084]" />
          </span>
          <div className="min-w-0 flex-1">
            <h1 className="text-[20px] font-semibold text-[#F8FAFC]">{agent.name}</h1>
            <p className="mt-0.5 text-[13px] text-[#94A3B8]">{agent.role}</p>
          </div>
          <TryAgentButton
            agentId={mapAgentIdToAction(agentId)}
            label={`Try ${agent.name.split(" ")[0]}`}
          />
        </div>

        {/* Responsibility + model context */}
        <div className="mt-5 grid grid-cols-1 gap-6 border-t border-white/8 pt-5 lg:grid-cols-[minmax(0,1.6fr)_minmax(0,1fr)]">
          <div>
            <p className="font-mono text-[11px] uppercase tracking-[0.12em] text-[#64748B]">
              Responsibility
            </p>
            <p className="mt-2 text-[15px] leading-relaxed text-[#F8FAFC]">{agent.description}</p>
          </div>
          <dl className="grid grid-cols-2 gap-4 border-t border-white/8 pt-4 lg:border-t-0 lg:border-l lg:pt-0 lg:pl-6">
            <div>
              <dt className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#64748B]">
                Model
              </dt>
              <dd className="mt-1 font-mono text-[13px] text-[#CBD5E1]">{agent.model}</dd>
            </div>
            <div>
              <dt className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#64748B]">
                Prompt version
              </dt>
              <dd className="mt-1 font-mono text-[13px] text-[#CBD5E1]">{agent.promptVersion}</dd>
            </div>
          </dl>
        </div>
      </div>

      {/* Metric cards */}
      <dl className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        {metrics.map((metric) => (
          <div key={metric.label} className={METRIC_CARD}>
            <dt className="font-mono text-[11px] uppercase tracking-[0.09em] text-[#64748B]">
              {metric.label}
            </dt>
            <dd className="mt-2 font-mono text-2xl font-semibold tabular-nums text-[#F8FAFC]">
              {metric.value}
            </dd>
            <p className="mt-1 text-[11px] text-[#64748B]">{metric.detail}</p>
          </div>
        ))}
      </dl>

      {/* Token breakdown */}
      <section aria-labelledby="token-breakdown">
        <SectionHeading
          id="token-breakdown"
          icon={Network}
          title="Token Breakdown"
          subtitle="Visible input, output, and cached tokens across this agent's recorded runs."
        />
        <div className={`${SECTION_CARD} p-5 sm:p-6`}>
          <StoryColumnChart
            title="Visible token consumption"
            description="Input, output, and cached tokens from fixed demo runs. No provider billing claim is made."
            summary={`${formatTokens(tokens)} visible tokens`}
            data={tokenBreakdown}
            barName="Tokens"
          />
        </div>
      </section>

      {/* Bounded dependencies */}
      <section aria-labelledby="dependencies">
        <SectionHeading
          id="dependencies"
          icon={Network}
          title="Bounded Dependencies"
          subtitle="This agent sees only the context required for its responsibility."
        />
        <div className={`${SECTION_CARD} p-5 sm:p-6`}>
          <ul className="flex flex-wrap gap-2">
            {agent.dependencies.map((dependency) => (
              <li
                key={dependency}
                className="inline-flex items-center gap-1.5 rounded-md border border-white/8 bg-white/5 px-2.5 py-1.5 text-[13px] text-[#CBD5E1]"
              >
                <CheckCircle2 className="h-3.5 w-3.5 text-[#00D084]" aria-hidden="true" />
                {dependency}
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* Run history */}
      <section aria-labelledby="run-history">
        <RunHistory
          runs={runItems}
          anchor={anchor}
          heading={
            <div>
              <h2
                id="run-history"
                className="flex items-center gap-2.5 text-lg font-semibold tracking-tight text-[#F8FAFC]"
              >
                <span className="grid h-7 w-7 shrink-0 place-items-center rounded-md border border-[#547D83]/40 bg-[#547D83]/20 text-[#B2D8DC]">
                  <ListChecks className="h-3.5 w-3.5" aria-hidden="true" />
                </span>
                Run History
              </h2>
              <p className="mt-1 text-[12px] text-[#64748B]">
                Every result has an explicit trigger, terminal state, latency, token count, and
                visible summary.
              </p>
            </div>
          }
        />
      </section>
    </div>
  );
}
